name: Rods
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69987
title: ROns Digitale Service
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373736'
    - '#007f35'
    - '#000000'
    - '#006633'
    - '#005500'
  brandStrength: 0.1875
  lightness: 0.028479597065597773
  saturation: 0.3989550727419555
  rhythmicContrast: 0.8575696642510593
purpose: []
