name: Rods
favicon: null
layout_spectrum: 0.62843
typography_spectrum: 0.69987
title: ROns Digitale Service
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373736'
    - '#007f35'
    - '#000000'
    - '#006633'
    - '#005500'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
